# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(268, 57)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.x_label = QtWidgets.QLabel(self.centralwidget)
        self.x_label.setGeometry(QtCore.QRect(9, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.x_label.setFont(font)
        self.x_label.setObjectName("x_label")
        self.x_value = QtWidgets.QLabel(self.centralwidget)
        self.x_value.setGeometry(QtCore.QRect(45, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.x_value.setFont(font)
        self.x_value.setObjectName("x_value")
        self.y_label = QtWidgets.QLabel(self.centralwidget)
        self.y_label.setGeometry(QtCore.QRect(99, 10, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.y_label.setFont(font)
        self.y_label.setObjectName("y_label")
        self.y_value = QtWidgets.QLabel(self.centralwidget)
        self.y_value.setGeometry(QtCore.QRect(135, 10, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.y_value.setFont(font)
        self.y_value.setObjectName("y_value")
        self.printButton = QtWidgets.QPushButton(self.centralwidget)
        self.printButton.setGeometry(QtCore.QRect(197, 6, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.printButton.setFont(font)
        self.printButton.setObjectName("printButton")
        self.sepButton = QtWidgets.QPushButton(self.centralwidget)
        self.sepButton.setGeometry(QtCore.QRect(197, 30, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.sepButton.setFont(font)
        self.sepButton.setObjectName("sepButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mouse Position"))
        self.x_label.setText(_translate("MainWindow", "X:"))
        self.x_value.setText(_translate("MainWindow", "xxxx"))
        self.y_label.setText(_translate("MainWindow", "Y:"))
        self.y_value.setText(_translate("MainWindow", "yyyy"))
        self.printButton.setText(_translate("MainWindow", "print"))
        self.sepButton.setText(_translate("MainWindow", "---"))
